export { default as rubImg } from './rub.png';
export { default as usdImg } from './usd.png';
export { default as euroImg } from './euro.png'
export { default as yuanImg } from './yuan.png';
export { default as liraImg } from './lira.png';
export { default as tugrikImg } from './tugrik.png';
export { default as dirhamImg } from './dirham.jpeg';
export { default as rupieesImg } from './rupiees.png'
export { default as tengeImg } from './tenge.webp';
export { default as wonImg } from './won.png';

export { default as btcImg } from './btc.png';
export { default as ethImg } from './eth.png';
export { default as xrpImg } from './xrp.png';
export { default as solImg } from './solana.png';
export { default as bnbImg } from './bnb.png';
export { default as usdtImg } from './usdt.png';
export { default as tonImg } from './ton.png';
export { default as trxImg } from './tron.png';